# description
description = "Was 8th Operational Regiment until January 2023, when it became the 14th Brigade as part of the Offensive Guard"
# socials
facebook = ""
telegram = ""
youtube = ""
twitter = ""