# description
description = "Was 98th Azov-Dnipro battalion of the TDF, before joining as 1st Mechanized Battalion in Azov Assault Brigade"
# socials
facebook = ""
telegram = ""
youtube = ""
twitter = ""