# description
description = "Formerly the DPR's 100th Motor Rifle Brigade. Renumbered as of January 2023 as 1st Army Corps came under the Russian Armed forces"
# socials
facebook = ""
telegram = ""
youtube = ""
twitter = ""